Resolve legacy peers
gridsuite/gridmerge-app pull request #112
Opened 2024-04-04 20:27 UTC by Tristan-WorkGH

Have to temporally resolve typescript version conflict use by react-scripts, dependent to typescript@^4, until the migration to Vite.

Ref gridsuite/commons-ui#350

2024-04-05 09:47 UTC, flomillot requested changes

2024-04-05 09:47 UTC, flomillot commented on src/components/merge-map.js
> +                                    className="tso"
Can't just use `sx` with a `Box` instead of this ?
Then no need CSS file.

2024-04-05 09:47 UTC, flomillot commented on src/components/app-top-bar.js
> +const classes = {
```suggestion
const styles = {
```

2024-04-05 09:47 UTC, flomillot commented on src/components/app-top-bar.js
> +const classes = {
(everywhere)

2024-04-05 09:47 UTC, flomillot commented on src/components/stepper.js
> +        [theme.breakpoints.down('sm')]: {
Not missing xs ?

2024-04-05 14:10 UTC, klesaulnier commented on src/components/stepper.js
> -        fontSize: '16px',
where did that go ?

2024-04-05 14:10 UTC, klesaulnier commented on src/components/stepper.js
> +};
change "...classes.stepperGridMargins" to a const then move this className to main class object

2024-04-08 09:58 UTC, Tristan-WorkGH commented on src/components/stepper.js
> -        fontSize: '16px',
it go in `styles` object at top of file

2024-04-08 15:07 UTC, flomillot approved these changes

2024-04-09 07:02 UTC, klesaulnier approved these changes

2024-04-09 07:06 UTC, merged