[WIP] Add business process in merge process
gridsuite/gridmerge-app pull request #45
Opened 2021-01-15 09:05 UTC by FranckLecuyer

2021-01-18 15:40 UTC, ChamseddineBhd approved these changes

2021-01-27 12:55 UTC, ChamseddineBhd requested changes

2021-01-27 12:55 UTC, ChamseddineBhd commented on src/components/workflows-configuration.js
> +                            <TextField
add  fullWidth={true} please

2021-01-27 12:55 UTC, ChamseddineBhd commented on src/utils/api.js
> +        '?businessProcess=' +
& instead of ?

2021-01-28 09:58 UTC, FranckLecuyer commented on src/components/workflows-configuration.js
> +                            <TextField
Done

2021-01-28 09:58 UTC, FranckLecuyer commented on src/utils/api.js
> +        '?businessProcess=' +
Corrected

2021-01-28 11:21 UTC, ChamseddineBhd requested changes

2021-01-28 11:21 UTC, ChamseddineBhd commented on src/translations/fr.json
> +    "businessProcess": "business process",
french translation !

2021-01-28 12:52 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "businessProcess": "business process",
Done

2021-01-28 13:27 UTC, ChamseddineBhd approved these changes

2021-01-28 16:58 UTC, merged