modify display of igm status list
gridsuite/gridmerge-app pull request #60
Opened 2021-04-12 13:02 UTC by JacquesBorsenberger

modify display of igm status list

# Conflicts:
#	src/components/processes-configuration.js

2021-04-13 11:25 UTC, FranckLecuyer requested changes

2021-04-13 11:25 UTC, FranckLecuyer commented on src/translations/en.json
> +    "ReplacedWith": "Replaced With",
Replaced with

2021-04-13 11:25 UTC, FranckLecuyer commented on src/components/country-state-item.js
> +                                {intl.formatMessage({ id: 'ReplacedWith' })}
In my opinion, the replacing business process should also be included in the 'replaced with' part

2021-04-16 15:12 UTC, niconoir approved these changes
I agree with Frank

2021-04-22 12:52 UTC, FranckLecuyer approved these changes

2021-05-05 07:47 UTC, merged